// _worker.js — Cloudflare Pages (advanced mode)
// Serves the static site AND proxies /claude to the Anthropic API so your
// API key never reaches the browser.
//
// Set these in Cloudflare Pages → your project → Settings → Variables and secrets:
//   ANTHROPIC_API_KEY   (required, mark as a secret)  your sk-ant-... key
//   CLAUDE_MODEL        (optional)  e.g. claude-haiku-4-5 for a cheaper model
//                                   (default: claude-sonnet-4-6)
//   PRICE_MODEL         (optional)  model for the premium-wine price search only
//                                   (default: CLAUDE_MODEL, then claude-sonnet-4-6)
//   SUPABASE_URL        (optional)  https://<project-ref>.supabase.co. With it and the two keys
//   SUPABASE_PUBLISHABLE_KEY          below, signed-in users are verified, metered per week and
//   SUPABASE_SECRET_KEY (secret)     checked for Pro (supabase/README.md). Without them, every
//                                   request is treated as signed out, as before.
// Bindings (Settings → Bindings):
//   PRICE_CACHE         (optional, KV namespace)  shares price-search results between all
//                                   users for 30 days. Without it, Cloudflare's per-data-centre
//                                   cache is used instead.

// NOTE: this file being present puts Cloudflare Pages into "advanced mode" —
// the _headers and _redirects files are then IGNORED by Pages for every
// response this worker returns (Cloudflare's own docs: custom headers in
// _headers "are not applied to responses generated by Pages Functions").
// That silently stripped manifest.json/sw.js of the headers PWA installability
// depends on, even though the files themselves validate fine offline.
// So: headers for the PWA-critical paths are set explicitly, right here.
//
// IMPORTANT: because this file exists, Cloudflare Pages runs entirely through
// this fetch() handler — the file-based routing in functions/ is NOT used at
// all (Cloudflare ignores the functions/ directory whenever _worker.js is
// present, for every path, not just the ones this file special-cases). Any
// request this handler doesn't recognise falls through to env.ASSETS.fetch()
// (static asset serving), never to a functions/*.js file. See docs/audit.md
// section 3 and docs/native-migration-spec.md section 1.3 for the routing
// investigation this depends on.

// Per-purpose max_tokens ceilings for /claude. The client sends `purpose`;
// the server picks the model (env var, never the client) and clamps
// max_tokens to this table — a client can ask for less, never more.
// One entry per real call site in the shipped app (see PR description for
// the full inventory of call sites this was checked against).
const CLAUDE_PURPOSE_LIMITS = {
  label_scan: 4096,       // pwa-screens-main.jsx — photo -> wine JSON
  list_scan: 8192,         // pwa-screens-main.jsx — photo of a wine list -> wine[]
  scancard: 4096,          // pwa-scancards.jsx — post-scan card deck copy
  price: 4096,             // pwa-components.jsx fetchRetailEstimate — retail price estimate
                            // (premium wines use purpose "price_search": handlePriceSearch,
                            // web search + shared cache, PRICE_MAX_TOKENS)
  explore: 4096,           // pwa-screens-explore.jsx — 4-tier bottle suggestions for a gap
  explore_info: 4096,      // pwa-screens-explore.jsx useClaudeData — region/varietal/similar-wines
  grape_quiz: 4096,        // pwa-grape-learning.js — generated grape quiz questions
  region_quiz: 4096,       // pwa-content-engine.js RegionQuizBank — generated region quiz questions
  match_explain: 4096,     // pwa-screens-detail.jsx — "why this wine matches you"
  vintage_info: 4096,      // pwa-screens-detail.jsx — vintage quality + drinking window
  education: 4096,         // pwa-screens-detail.jsx — grape/vocabulary deep-dive
  wine_qa: 300,            // pwa-vinny.js — "Ask Vinny" wine Q&A (prompts/vinny.txt). Answers are
                            // up to 3 short sentences (~60 words); this caps it well above that,
                            // as a backstop if the model ever ignores the length instruction.
  sommelier_script: 4096,  // pwa-screens-home.jsx / pwa-screens-aux.jsx / pwa-screens-wineiq.jsx
  learn_article: 4096,     // pwa-screens-learn.jsx — generated learning article body
  winedna_summary: 4096    // pwa-screens-wineiq.jsx — Wine DNA personality summary
};

const ALLOWED_ORIGINS = [
  "https://vinterest.app",
  "https://vinterest.pages.dev",
  "capacitor://localhost",
  "https://localhost"
];
// Cloudflare Pages preview deployments get a per-build subdomain
// (<hash>.vinterest.pages.dev). The review workflow in
// docs/native-migration-spec.md section 6 depends on exercising those
// previews, so they're allowed too.
const PREVIEW_ORIGIN_RE = /^https:\/\/[a-z0-9-]+\.vinterest\.pages\.dev$/;

const MAX_BODY_BYTES = 6 * 1024 * 1024; // headroom above a 1024px-JPEG scan payload

const RATE_LIMIT_WINDOW_MS = 5 * 60 * 1000;
const RATE_LIMIT_MAX = 40; // generous fair-use cap, per spec D5 — a cost guard, not a product limit
// Best-effort, per-isolate. Not durable across Cloudflare's many isolates/colos; it guards signed-
// out use. Signed-in users are also metered per week in Supabase (gateAccount).
const _rateLimitBuckets = new Map();

export default {
  async fetch(request, env, ctx) {
    const url = new URL(request.url);
    if (url.pathname === "/me") {
      if (request.method === "OPTIONS") return cors(new Response(null, { status: 204 }));
      if (request.method !== "GET") return json(405, { error: "Method not allowed" });
      return handleMe(request, env);
    }
    if (url.pathname === "/config") {
      if (request.method === "OPTIONS") return cors(new Response(null, { status: 204 }));
      if (request.method !== "GET") return json(405, { error: "Method not allowed" });
      // The public sign-in settings, for an app build that wasn't given them (Account.loadRemoteConfig).
      return json(200, { supabase: env.SUPABASE_URL && env.SUPABASE_PUBLISHABLE_KEY ? { url: env.SUPABASE_URL, key: env.SUPABASE_PUBLISHABLE_KEY } : null });
    }
    if (url.pathname === "/account/delete") {
      if (request.method === "OPTIONS") return cors(new Response(null, { status: 204 }));
      if (request.method !== "POST") return json(405, { error: "Method not allowed" });
      return handleAccountDelete(request, env);
    }
    if (url.pathname === "/claude") {
      if (request.method === "OPTIONS") return cors(new Response(null, { status: 204 }));
      if (request.method !== "POST") return json(405, { error: "Method not allowed" });
      return handleClaude(request, env, ctx);
    }

    const res = await env.ASSETS.fetch(request);

    if (url.pathname === "/manifest.json") {
      const headers = new Headers(res.headers);
      headers.set("Content-Type", "application/manifest+json");
      headers.set("Cache-Control", "no-cache, must-revalidate");
      return new Response(res.body, { status: res.status, headers });
    }

    if (url.pathname === "/sw.js") {
      const headers = new Headers(res.headers);
      headers.set("Content-Type", "application/javascript");
      headers.set("Cache-Control", "no-cache, no-store, must-revalidate");
      headers.set("Service-Worker-Allowed", "/");
      return new Response(res.body, { status: res.status, headers });
    }

    if (url.pathname === "/index.html" || url.pathname === "/") {
      const headers = new Headers(res.headers);
      headers.set("Cache-Control", "no-cache, must-revalidate");
      return new Response(res.body, { status: res.status, headers });
    }

    if (url.pathname.startsWith("/icons/")) {
      const headers = new Headers(res.headers);
      headers.set("Cache-Control", "public, max-age=86400");
      headers.set("Access-Control-Allow-Origin", "*");
      return new Response(res.body, { status: res.status, headers });
    }

    if (url.pathname.endsWith(".jsx") || url.pathname.endsWith(".js")) {
      const headers = new Headers(res.headers);
      headers.set("Cache-Control", "no-cache, must-revalidate");
      return new Response(res.body, { status: res.status, headers });
    }

    return res;
  }
};

function originAllowed(origin) {
  if (!origin) return true; // no Origin header — native/webview clients; rate limiting is the backstop
  return ALLOWED_ORIGINS.includes(origin) || PREVIEW_ORIGIN_RE.test(origin);
}

function clientIp(request) {
  return request.headers.get("cf-connecting-ip") || "unknown";
}

function rateLimited(ip) {
  const now = Date.now();
  let hits = _rateLimitBuckets.get(ip);
  if (!hits) { hits = []; _rateLimitBuckets.set(ip, hits); }
  while (hits.length && now - hits[0] > RATE_LIMIT_WINDOW_MS) hits.shift();
  if (hits.length >= RATE_LIMIT_MAX) return true;
  hits.push(now);
  // Opportunistic cleanup so the map doesn't grow unbounded under distributed traffic.
  if (_rateLimitBuckets.size > 5000) {
    for (const [key, arr] of _rateLimitBuckets) {
      while (arr.length && now - arr[0] > RATE_LIMIT_WINDOW_MS) arr.shift();
      if (arr.length === 0) _rateLimitBuckets.delete(key);
    }
  }
  return false;
}

async function handleClaude(request, env, ctx) {
  const key = env.ANTHROPIC_API_KEY;
  if (!key) {
    return json(500, { error: "Server is missing ANTHROPIC_API_KEY. Add it in Cloudflare Pages → Settings → Variables and secrets, then redeploy.", code: "missing_api_key" });
  }

  const origin = request.headers.get("origin");
  if (!originAllowed(origin)) {
    return json(403, { error: "Origin not allowed.", code: "origin_denied" });
  }

  const ip = clientIp(request);
  if (rateLimited(ip)) {
    return json(429, { error: "Too many requests. Please slow down and try again shortly.", code: "rate_limited" });
  }

  const contentLength = request.headers.get("content-length");
  if (contentLength && Number(contentLength) > MAX_BODY_BYTES) {
    return json(413, { error: "Request body too large.", code: "body_too_large" });
  }

  let rawBody;
  try { rawBody = await request.text(); }
  catch (e) { return json(400, { error: "Could not read request body.", code: "unreadable_body" }); }
  if (rawBody.length > MAX_BODY_BYTES) {
    return json(413, { error: "Request body too large.", code: "body_too_large" });
  }

  let payload;
  try { payload = JSON.parse(rawBody); }
  catch (e) { return json(400, { error: "Invalid JSON body.", code: "invalid_json" }); }

  const purpose = payload.purpose;
  if (purpose !== "price_search" && !CLAUDE_PURPOSE_LIMITS[purpose]) {
    return json(400, { error: "Request must include a valid purpose.", code: "invalid_purpose" });
  }
  // Signed in: verified, metered for the week, and checked for Pro. Signed out: as before.
  const gate = await gateAccount(request, env, purpose);
  if (gate.response) return gate.response;

  // Premium-wine price search: built here from the wine's fields, never from client prompts,
  // so /claude can't be used as an open web-search proxy.
  if (purpose === "price_search") return handlePriceSearch(payload, env, key, ctx);
  const purposeCap = CLAUDE_PURPOSE_LIMITS[purpose];

  const messages = payload.messages;
  if (!Array.isArray(messages) || messages.length === 0) {
    return json(400, { error: "Request must include a non-empty messages[] array.", code: "invalid_messages" });
  }

  // The model always comes from the environment — never from the request.
  const model = env.CLAUDE_MODEL || "claude-sonnet-4-6";
  const max_tokens = Math.min(Number(payload.max_tokens) || purposeCap, purposeCap);

  try {
    const r = await fetch("https://api.anthropic.com/v1/messages", {
      method: "POST",
      headers: {
        "content-type": "application/json",
        "x-api-key": key,
        "anthropic-version": "2023-06-01"
      },
      body: JSON.stringify({ model, max_tokens, messages })
    });
    const data = await r.json();
    if (!r.ok) {
      const msg = (data && data.error && data.error.message) || "Anthropic API error.";
      return json(r.status, { error: msg, code: "anthropic_error" });
    }
    const text = (data.content || [])
      .filter((b) => b.type === "text")
      .map((b) => b.text)
      .join("");
    return json(200, { text });
  } catch (e) {
    return json(502, { error: "Failed to reach Anthropic: " + (e && e.message ? e.message : String(e)), code: "upstream_unreachable" });
  }
}

/* ── Accounts (Supabase) ──
   Sign-in is optional (spec D1). A request without a sign-in token is handled as before (the
   per-IP rate limit above). With one, the token is checked with Supabase, the call is counted
   against a weekly fair-use cap for that user (use_quota, supabase/migrations/0002), and Pro-only
   purposes need Pro in `entitlements`, which only the server writes. The caps are cost guards,
   set generously, never product limits (spec D5). */
const FAIR_USE = {
  free: { label_scan: 100, list_scan: 0, price_search: 50, _other: 500 },
  pro:  { label_scan: 600, list_scan: 150, price_search: 300, _other: 3000 },
};
const PRO_ONLY = { list_scan: "Wine list scanning is part of Vinterest Pro." };
const AUTH_CACHE_MS = 5 * 60 * 1000;
const _authCache = new Map();

function accountsOn(env) { return !!(env.SUPABASE_URL && env.SUPABASE_PUBLISHABLE_KEY && env.SUPABASE_SECRET_KEY); }

/* The signed-in user ({id, email}), null when signed out, or {invalid:true} for a token Supabase
   doesn't accept (expired or forged). */
async function authUser(request, env) {
  const m = /^Bearer\s+(\S+)$/i.exec(request.headers.get("authorization") || "");
  if (!m || !accountsOn(env)) return null;
  const token = m[1], now = Date.now();
  const hit = _authCache.get(token);
  if (hit && hit.until > now) return hit.user;
  const r = await fetch(`${env.SUPABASE_URL}/auth/v1/user`, { headers: { apikey: env.SUPABASE_PUBLISHABLE_KEY, authorization: `Bearer ${token}` } });
  if (r.status === 401 || r.status === 403) return { invalid: true };
  if (!r.ok) throw new Error("auth_unavailable");
  const u = await r.json();
  const user = { id: u.id, email: u.email || null };
  _authCache.set(token, { user, until: now + AUTH_CACHE_MS });
  if (_authCache.size > 5000) for (const [k, v] of _authCache) if (v.until <= now) _authCache.delete(k);
  return user;
}

/* The database, as the server (the secret key; never sent to a browser). */
function db(env, path, init = {}) {
  return fetch(`${env.SUPABASE_URL}/rest/v1/${path}`, { ...init, headers: { apikey: env.SUPABASE_SECRET_KEY, "content-type": "application/json", ...(init.headers || {}) } });
}
async function tierOf(env, userId) {
  const r = await db(env, `entitlements?user_id=eq.${encodeURIComponent(userId)}&select=tier,expires_at`);
  if (!r.ok) return "free";
  const [e] = await r.json();
  return e && e.tier === "pro" && (!e.expires_at || new Date(e.expires_at) > new Date()) ? "pro" : "free";
}
function capFor(tier, kind) { const t = FAIR_USE[tier] || FAIR_USE.free; return kind in t ? t[kind] : t._other; }
function weekStart(d = new Date()) {
  const x = new Date(Date.UTC(d.getUTCFullYear(), d.getUTCMonth(), d.getUTCDate()));
  x.setUTCDate(x.getUTCDate() - ((x.getUTCDay() + 6) % 7));
  return x.toISOString().slice(0, 10);
}

/* {response} to send instead of calling Claude, or {user, tier} to carry on. */
async function gateAccount(request, env, purpose) {
  let user;
  try { user = await authUser(request, env); }
  catch (e) { return {}; } // Supabase unreachable: don't block the app; the IP limit still applies
  if (user && user.invalid) return { response: json(401, { error: "Your sign-in has expired. Sign in again to carry on.", code: "auth_expired" }) };
  if (!user) {
    if (PRO_ONLY[purpose] && accountsOn(env)) return { response: json(402, { error: `${PRO_ONLY[purpose]} Sign in to use Pro.`, code: "pro_required", signIn: true }) };
    return {};
  }
  const tier = await tierOf(env, user.id);
  if (PRO_ONLY[purpose] && tier !== "pro") return { response: json(402, { error: PRO_ONLY[purpose], code: "pro_required" }) };
  const r = await db(env, "rpc/use_quota", { method: "POST", body: JSON.stringify({ p_user: user.id, p_kind: purpose, p_cap: capFor(tier, purpose) }) });
  if (r.ok && (await r.json()) === null) {
    return { response: json(429, { error: "You've reached this week's fair-use limit for this. It resets on Monday.", code: "fair_use" }) };
  }
  return { user, tier };
}

/* GET /me: who's signed in, their plan, and this week's usage against the caps. */
async function handleMe(request, env) {
  const origin = request.headers.get("origin");
  if (!originAllowed(origin)) return json(403, { error: "Origin not allowed.", code: "origin_denied" });
  let user;
  try { user = await authUser(request, env); }
  catch (e) { return json(503, { error: "Accounts are unavailable right now.", code: "auth_unavailable" }); }
  if (user && user.invalid) return json(401, { error: "Your sign-in has expired.", code: "auth_expired" });
  if (!user) return json(200, { signedIn: false, accounts: accountsOn(env), tier: "free" });
  const tier = await tierOf(env, user.id);
  const week = weekStart();
  const r = await db(env, `usage_counters?user_id=eq.${encodeURIComponent(user.id)}&period_start=eq.${week}&select=kind,count`);
  const usage = r.ok ? Object.fromEntries((await r.json()).map((u) => [u.kind, u.count])) : {};
  return json(200, { signedIn: true, accounts: true, email: user.email, tier, week, usage, caps: FAIR_USE[tier] });
}

/* POST /account/delete: deletes the signed-in user for good (Apple requires this inside the app).
   The auth user goes first: every table references auth.users on delete cascade, so if that fails
   nothing has changed and the app keeps its data. The row deletes after it are a second guarantee,
   so no table is ever left holding their rows if a cascade is missing. */
const USER_TABLES = ["wines", "user_docs", "usage_counters", "entitlements"];
async function handleAccountDelete(request, env) {
  const origin = request.headers.get("origin");
  if (!originAllowed(origin)) return json(403, { error: "Origin not allowed.", code: "origin_denied" });
  if (!accountsOn(env)) return json(503, { error: "Accounts aren't set up on this server.", code: "accounts_off" });
  let user;
  try { user = await authUser(request, env); }
  catch (e) { return json(503, { error: "We couldn't reach your account. Check your connection and try again.", code: "auth_unavailable" }); }
  if (!user || user.invalid) return json(401, { error: "Sign in again, then delete your account.", code: "auth_expired" });
  const id = encodeURIComponent(user.id);

  // TODO(RevenueCat): once purchases go through RevenueCat, cancel or detach this user's
  // subscription here (DELETE /v1/subscribers/{app_user_id}) before their account goes, and tell
  // them that an App Store subscription is cancelled in Settings, not by deleting the account.
  // TODO(Sign in with Apple): once Sign in with Apple exists, revoke the user's Apple token here
  // (POST https://appleid.apple.com/auth/revoke with the stored refresh token), as Apple requires.

  let r;
  try { r = await fetch(`${env.SUPABASE_URL}/auth/v1/admin/users/${id}`, { method: "DELETE", headers: { apikey: env.SUPABASE_SECRET_KEY } }); }
  catch (e) { r = null; }
  if (!r || (!r.ok && r.status !== 404)) return json(502, { error: "Your account couldn't be deleted just now. Nothing was removed. Try again in a minute.", code: "delete_failed" });
  await Promise.all(USER_TABLES.map((t) => db(env, `${t}?user_id=eq.${id}`, { method: "DELETE" }).catch(() => null)));
  for (const [k, v] of _authCache) if (v.user && v.user.id === user.id) _authCache.delete(k);
  return json(200, { deleted: true });
}

/* ── Price search for premium wines ──
   One web search of current shop listings for a wine in the user's market, shared between all
   users (KV PRICE_CACHE if bound, else the Cache API) for PRICE_TTL_S. The first person to scan a
   given wine and vintage in a market pays for the search; everyone after gets it free. Returns
   {text: JSON of {low, mid, high, currency, tier, note, source:'search'}, cached} or {text:''}
   when nothing could be found (the app then falls back to its ordinary estimate).
   The app waits at most PRICE_WAIT_MS: a slower search returns {text:'', pending:true} and keeps
   running (ctx.waitUntil) so its answer is saved for the next person to open that wine. */
const PRICE_TTL_S = 30 * 24 * 3600;
const PRICE_MAX_TOKENS = 2048;
const PRICE_WAIT_MS = 20000;      // how long the app waits before showing its estimate
const PRICE_UPSTREAM_MS = 60000;  // give up on the search itself after this
const MARKET_CODE_RE = /^[A-Z]{3}$/;
const COUNTRY_RE = /^[A-Z]{2}$/;

function _slug(s) {
  return String(s || "").normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLowerCase()
    .replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "").slice(0, 80);
}
function priceCacheKey(w, m) {
  const v = /^(19|20)\d{2}$/.test(String(w.vintage || "")) ? String(w.vintage) : "nv";
  return `price:v1:${m.code}:${_slug(w.producer)}:${_slug(w.name)}:${v}`;
}
async function priceCacheGet(env, k) {
  try {
    if (env.PRICE_CACHE) return await env.PRICE_CACHE.get(k);
    const hit = await caches.default.match(new Request("https://price-cache.vinterest.internal/" + encodeURIComponent(k)));
    return hit ? await hit.text() : null;
  } catch (e) { return null; }
}
async function priceCachePut(env, k, value) {
  try {
    if (env.PRICE_CACHE) return await env.PRICE_CACHE.put(k, value, { expirationTtl: PRICE_TTL_S });
    await caches.default.put(new Request("https://price-cache.vinterest.internal/" + encodeURIComponent(k)),
      new Response(value, { headers: { "Cache-Control": `public, max-age=${PRICE_TTL_S}` } }));
  } catch (e) {}
}
function _clean(s, n) { return String(s || "").replace(/[\r\n"]+/g, " ").trim().slice(0, n || 120); }

async function handlePriceSearch(payload, env, key, ctx) {
  const w = payload.wine || {}, m = payload.market || {};
  if (!w.name || !MARKET_CODE_RE.test(String(m.code || ""))) return json(400, { error: "price_search needs wine.name and market.code.", code: "invalid_price_search" });
  const k = priceCacheKey(w, m);
  const hit = await priceCacheGet(env, k);
  if (hit) return json(200, { text: hit, cached: true });

  const model = env.PRICE_MODEL || env.CLAUDE_MODEL || "claude-sonnet-4-6";
  // The basic search tool: a price is in the result snippets, and it's far quicker than the
  // dynamic-filtering variant, which runs code over every page it reads.
  const tool = { type: "web_search_20250305", name: "web_search", max_uses: 2 };
  const country = String(m.country || "").toUpperCase();
  if (COUNTRY_RE.test(country)) tool.user_location = { type: "approximate", country };
  const vintage = /^(19|20)\d{2}$/.test(String(w.vintage || "")) ? String(w.vintage) : "";
  const prompt =
    `Find what this wine costs today in wine shops in ${_clean(m.label, 40) || country} (${m.code}), for one 75cl bottle.\n` +
    `Wine: ${_clean(w.producer)} ${_clean(w.name)} ${vintage || "(current release)"}. ${_clean(w.region)}, ${_clean(w.country, 40)}. Type: ${_clean(w.type, 20)}.\n` +
    `Search current listings from wine merchants and shops in that market. Prefer the ${vintage ? vintage + " vintage" : "current release"}; if it isn't listed, use the nearest current vintage and say so. ` +
    `Ignore auction results, en primeur / in-bond prices, magnums and restaurant prices; divide case prices by the number of bottles. Convert other currencies to ${m.code} approximately.\n` +
    `Return ONLY JSON, no markdown: {"low":INT,"mid":INT,"high":INT,"currency":"${m.code}","tier":"entry|everyday|premium|luxury|ultra-luxury","note":"one sentence on where the range comes from, e.g. which vintage and the kind of shops","found":true}. ` +
    `If you can't find real listings, return {"found":false}.`;

  const work = (async () => {
    const messages = [{ role: "user", content: prompt }];
    const abort = new AbortController();
    const timer = setTimeout(() => abort.abort(), PRICE_UPSTREAM_MS);
    try {
      let data = null;
      for (let turn = 0; turn < 2; turn++) {
        const r = await fetch("https://api.anthropic.com/v1/messages", {
          method: "POST", signal: abort.signal,
          headers: { "content-type": "application/json", "x-api-key": key, "anthropic-version": "2023-06-01" },
          body: JSON.stringify({ model, max_tokens: PRICE_MAX_TOKENS, messages, tools: [tool] })
        });
        data = await r.json();
        if (!r.ok) return { error: (data && data.error && data.error.message) || "Anthropic API error.", status: r.status };
        // A long search can pause mid-turn; continue it once.
        if (data.stop_reason !== "pause_turn") break;
        messages.push({ role: "assistant", content: data.content });
      }
      const text = (data.content || []).filter((b) => b.type === "text").map((b) => b.text).join("");
      const s = text.indexOf("{"), e = text.lastIndexOf("}");
      let parsed = null;
      try { parsed = s >= 0 && e > s ? JSON.parse(text.slice(s, e + 1)) : null; } catch (err) {}
      if (!(parsed && parsed.found !== false && Number(parsed.mid) > 0)) return { text: "" };
      const out = JSON.stringify({
        low: Math.round(Number(parsed.low) || Number(parsed.mid)), mid: Math.round(Number(parsed.mid)), high: Math.round(Number(parsed.high) || Number(parsed.mid)),
        currency: m.code, tier: parsed.tier || null, note: _clean(parsed.note, 240) || null, source: "search", at: Date.now()
      });
      await priceCachePut(env, k, out);
      return { text: out };
    } catch (e) {
      return { error: "Failed to reach Anthropic: " + (e && e.message ? e.message : String(e)), status: 502 };
    } finally { clearTimeout(timer); }
  })();
  // Let the search finish (and be saved) even after the app stops waiting.
  if (ctx && ctx.waitUntil) ctx.waitUntil(work.catch(() => {}));
  const res = await Promise.race([work, new Promise((ok) => setTimeout(() => ok(null), PRICE_WAIT_MS))]);
  if (!res) return json(200, { text: "", pending: true });
  if (res.error) return json(res.status || 502, { error: res.error, code: "anthropic_error" });
  return json(200, { text: res.text, cached: false });
}

function cors(res) {
  res.headers.set("access-control-allow-origin", "*");
  res.headers.set("access-control-allow-headers", "content-type, authorization");
  res.headers.set("access-control-allow-methods", "GET, POST, OPTIONS");
  return res;
}
function json(status, obj) {
  return cors(new Response(JSON.stringify(obj), {
    status,
    headers: { "content-type": "application/json" }
  }));
}
