/* Vinterest PWA — Home, Scan, Wine Identified screens */

function HomeScreen({nav}){
  const [profileTab,setProfileTab]=React.useState(0);
  // Read cached scripts generated by TasteProfileScreen
  const typeKeys=['red','white','rose','sparkling'];
  const allHomeWines=WineHistory.getAll();
  function getCachedScript(typeKey){
    const count=allHomeWines.filter(w=>(w.type||'').toLowerCase().replace('é','e')===typeKey).length;
    if(!count) return null;
    return localStorage.getItem(`vinterest_script_v2_${typeKey}_n${count}`)||null;
  }
  const scripts=[
    {col:'#8B1A2F',label:'Reds',     script:getCachedScript('red')     ||'"Open your Reds profile to generate your personalised script."'},
    {col:'#B8963E',label:'Whites',   script:getCachedScript('white')   ||'"Open your Whites profile to generate your personalised script."'},
    {col:'#C47A8A',label:'Rosé',     script:getCachedScript('rose')    ||'"Open your Rosé profile to generate your personalised script."'},
    {col:'#5E8FA8',label:'Sparkling',script:getCachedScript('sparkling')||'"Open your Sparkling profile to generate your personalised script."'},
  ];
  return(
    <div style={{flex:1,display:'flex',flexDirection:'column',overflowY:'auto'}}>
      {/* Header */}
      <div style={{padding:'16px 20px 0',display:'flex',justifyContent:'space-between',alignItems:'center',background:C.white}}>
        <div>
          <div style={{fontSize:15,color:C.mid,fontFamily:C.P}}>Good evening</div>
          <div style={{fontSize:24,fontWeight:800,color:C.ink,fontFamily:C.P,letterSpacing:'-0.5px'}}>Vinterest</div>
        </div>
        <div onClick={()=>nav('profile')} style={{width:40,height:40,borderRadius:20,background:C.crSoft,display:'flex',alignItems:'center',justifyContent:'center',cursor:'pointer'}}>
          <Icon n="user" sz={20} col={C.cr}/>
        </div>
      </div>

      <div style={{padding:'16px 20px 0',display:'flex',flexDirection:'column',gap:12}}>
        {/* QUICK ACTIONS label */}
        <div style={{fontSize:14,fontWeight:600,color:C.mid,letterSpacing:'0.08em',textTransform:'uppercase',fontFamily:C.P}}>Quick Actions</div>

        {/* Primary scan CTA */}
        <div onClick={()=>nav('scan')} style={{background:C.ink,borderRadius:20,padding:'18px 20px',display:'flex',alignItems:'center',gap:14,cursor:'pointer',position:'relative',overflow:'hidden'}}>
          <div style={{position:'absolute',right:-16,top:-16,width:110,height:110,borderRadius:55,background:'rgba(139,26,47,0.3)'}}/>
          <div style={{width:52,height:52,borderRadius:14,background:C.cr,display:'flex',alignItems:'center',justifyContent:'center',flexShrink:0,zIndex:1,boxShadow:`0 4px 16px ${C.cr}50`}}>
            <Icon n="camera" sz={26} col="#fff"/>
          </div>
          <div style={{flex:1,zIndex:1}}>
            <div style={{fontSize:20,fontWeight:700,color:'#fff',fontFamily:C.P}}>Scan a Bottle</div>
            <div style={{fontSize:15,color:'rgba(255,255,255,0.5)',fontFamily:C.P,marginTop:1}}>Point at any label to identify</div>
          </div>
          <Icon n="chevron" sz={16} col="rgba(255,255,255,0.35)"/>
        </div>

        {/* Secondary actions */}
        <div style={{display:'flex',gap:10}}>
          {[{i:'fork',l:'Restaurant',s:'restaurant',hint:'Scan menus, get scripts'},{i:'cart',l:'Shopping',s:'shopping',hint:'Match wines in store'}].map((a,i)=>(
            <div key={i} onClick={()=>nav(a.s)} style={{flex:1,background:C.white,borderRadius:16,padding:'14px',display:'flex',flexDirection:'column',gap:8,border:`1px solid ${C.line}`,cursor:'pointer'}}>
              <div style={{width:38,height:38,borderRadius:10,background:C.crSoft,display:'flex',alignItems:'center',justifyContent:'center'}}>
                <Icon n={a.i} sz={20} col={C.cr}/>
              </div>
              <div>
                <div style={{fontSize:17,fontWeight:600,color:C.ink,fontFamily:C.P}}>{a.l}</div>
                <div style={{fontSize:14,color:C.mid,fontFamily:C.P}}>{a.hint}</div>
              </div>
            </div>
          ))}
        </div>

        {/* Taste Profile with category tabs */}
        <div style={{fontSize:14,fontWeight:600,color:C.mid,letterSpacing:'0.08em',textTransform:'uppercase',fontFamily:C.P,display:'flex',justifyContent:'space-between',alignItems:'center'}}>
          <span>Your Taste Profile</span>
          <span onClick={()=>nav('profile')} style={{color:C.cr,cursor:'pointer',textTransform:'none',fontSize:15,letterSpacing:'normal',fontWeight:600}}>Full Profile →</span>
        </div>
        <Card style={{padding:0,overflow:'hidden'}}>
          <div style={{display:'flex',borderBottom:`1px solid ${C.line}`}}>
            {scripts.map((t,i)=>(
              <div key={i} onClick={()=>setProfileTab(i)} style={{flex:1,textAlign:'center',padding:'10px 4px',cursor:'pointer',borderBottom:i===profileTab?`2px solid ${t.col}`:'2px solid transparent',marginBottom:-1}}>
                <div style={{width:8,height:8,borderRadius:4,background:t.col,margin:'0 auto 3px'}}/>
                <span style={{fontSize:13,fontWeight:i===profileTab?700:400,color:i===profileTab?t.col:C.mid,fontFamily:C.P}}>{t.label}</span>
              </div>
            ))}
          </div>
          <div style={{padding:'12px 14px'}}>
            <div style={{fontSize:15,color:C.ink2,fontFamily:C.P,fontStyle:'italic',lineHeight:1.6,marginBottom:10}}>{scripts[profileTab].script}</div>
            <div style={{display:'flex',gap:8}}>
              <div onClick={()=>{try{navigator.clipboard.writeText(scripts[profileTab].script.replace(/"/g,''))}catch(e){}}} style={{flex:1,background:scripts[profileTab].col,borderRadius:8,padding:'8px',textAlign:'center',cursor:'pointer'}}>
                <span style={{fontSize:14,fontWeight:600,color:'#fff',fontFamily:C.P}}>Copy Script</span>
              </div>
              <div onClick={()=>nav('profile')} style={{flex:1,background:C.offWhite,borderRadius:8,padding:'8px',textAlign:'center',border:`1px solid ${C.line}`,cursor:'pointer'}}>
                <span style={{fontSize:14,fontWeight:500,color:C.ink2,fontFamily:C.P}}>Edit Preferences</span>
              </div>
            </div>
          </div>
        </Card>

        {/* My Wines — recent scans */}
        {(()=>{
          const wines=WineHistory.getAll();
          return(
            <div style={{paddingBottom:16}}>
              <div style={{fontSize:14,fontWeight:600,color:C.mid,letterSpacing:'0.08em',textTransform:'uppercase',fontFamily:C.P,display:'flex',justifyContent:'space-between',alignItems:'center',marginBottom:10}}>
                <span>My Wines</span>
                <span onClick={()=>nav('mywines')} style={{color:C.cr,cursor:'pointer',textTransform:'none',fontSize:15,letterSpacing:'normal',fontWeight:600}}>{wines.length>0?`${wines.length} wines →`:'View All →'}</span>
              </div>
              {wines.length===0?(
                <Card style={{padding:20,textAlign:'center'}}>
                  <div style={{fontSize:28,marginBottom:8}}>🍷</div>
                  <div style={{fontSize:17,fontWeight:600,color:C.ink,fontFamily:C.P}}>No wines scanned yet</div>
                  <div style={{fontSize:15,color:C.mid,fontFamily:C.P,marginTop:4}}>Tap Scan to identify your first bottle</div>
                </Card>
              ):(
                <div style={{display:'flex',flexDirection:'column',gap:8}}>
                  {wines.slice(0,3).map((w,i)=>(
                    <Card key={i} style={{padding:10,cursor:'pointer'}} onClick={()=>nav('mywines')}>
                      <div style={{display:'flex',alignItems:'center',gap:10}}>
                        <div style={{width:38,height:50,borderRadius:8,background:C.crSoft,flexShrink:0,display:'flex',alignItems:'center',justifyContent:'center',border:`1px solid ${C.crDim}`}}>
                          <Icon n="wine" sz={18} col={C.cr}/>
                        </div>
                        <div style={{flex:1,minWidth:0}}>
                          <div style={{fontSize:16,fontWeight:600,color:C.ink,fontFamily:C.P,whiteSpace:'nowrap',overflow:'hidden',textOverflow:'ellipsis'}}>{w.name}</div>
                          <div style={{fontSize:14,color:C.mid,fontFamily:C.P}}>{w.region||w.country} · {w.vintage||'NV'}</div>
                          {w.rating>0&&<div style={{display:'inline-flex',alignItems:'baseline',gap:2,marginTop:3}}>
                            <span style={{fontSize:16,fontWeight:700,color:C.amber,fontFamily:C.P}}>{w.rating}</span>
                            <span style={{fontSize:13,color:C.mid,fontFamily:C.P}}>/100</span>
                          </div>}
                        </div>
                        <div style={{textAlign:'right',flexShrink:0}}>
                          <div style={{fontSize:13,color:C.mid,fontFamily:C.P}}>{w.times_consumed||1}x scanned</div>
                          {w.type&&<div style={{fontSize:13,color:C.cr,fontFamily:C.P,fontWeight:500,textTransform:'capitalize',marginTop:2}}>{w.type}</div>}
                        </div>
                      </div>
                    </Card>
                  ))}
                </div>
              )}
            </div>
          );
        })()}
      </div>
    </div>
  );
}

/* ── SCAN CAMERA ── */
function ScanScreen({nav,back}){
  const videoRef=React.useRef(null);
  const streamRef=React.useRef(null);
  const [phase,setPhase]=React.useState('viewfinder'); // viewfinder | processing
  const [capturedImg,setCapturedImg]=React.useState(null);
  const [mode,setMode]=React.useState('bottle'); // bottle | list
  const [camErr,setCamErr]=React.useState(false);

  React.useEffect(()=>{
    navigator.mediaDevices?.getUserMedia({video:{facingMode:'environment',width:{ideal:1080},height:{ideal:1920}}})
      .then(s=>{ streamRef.current=s; if(videoRef.current) videoRef.current.srcObject=s; })
      .catch(()=>setCamErr(true));
    return ()=>{ if(streamRef.current) streamRef.current.getTracks().forEach(t=>t.stop()); };
  },[]);

  const LABEL_PROMPT=`You are an expert sommelier with exceptional vision. Analyse this photo and identify any wine bottle label visible — even if partially obscured, at an angle, or in low light. Do your best with whatever text or imagery you can make out. Return ONLY valid JSON (no markdown, no code fences) with these fields: {"name":"full wine name","producer":"winery","vintage":2018,"region":"region","sub_region":"sub-region or empty string","country":"country","type":"red|white|rosé|sparkling","grapes":["Primary Grape"],"body":0.85,"tannins":0.80,"acidity":0.60,"sweetness":0.05,"abv":13.5,"tasting_notes":["Note1","Note2","Note3"],"food_pairings":["Food1","Food2","Food3"],"price_usd":50,"community_rating":4.5,"description":"2-3 sentence approachable description.","why_you_will_like_this":"1-2 sentences personalised to a wine lover.","body_plain":"How heavy it feels in your mouth","tannins_plain":"That drying grip on your gums","acidity_plain":"How zingy and fresh it tastes","sweetness_plain":"Dry means barely any sugar"}. Only return {"error":"no_wine_label"} if there is absolutely no wine bottle or label anywhere in the image.`;

  const LIST_PROMPT=`You are a sommelier reading a wine list. Extract EVERY wine from this image in the order they appear — do not skip any. Return ONLY valid JSON (no markdown): {"wines":[{"n":"wine name","t":"red|white|rosé|sparkling","r":"region","c":"country","v":2020,"p":"price as shown e.g. £85"}]}. Include ALL wines visible. Do not stop early.`;

  function capturePhoto(){
    if(!videoRef.current||!videoRef.current.videoWidth){
      if(streamRef.current) streamRef.current.getTracks().forEach(t=>t.stop());
      setPhase('processing');
      if(mode==='list'){
        sessionStorage.setItem('vinterest_winelist_result',JSON.stringify({demo:true,reason:'camera_not_ready'}));
        setTimeout(()=>nav('winelist'),1600);
      } else {
        sessionStorage.setItem('vinterest_scan_result',JSON.stringify({demo:true,reason:'camera_not_ready'}));
        setTimeout(()=>nav('identified'),1600);
      }
      return;
    }
    // Capture frame FIRST, then stop stream (stopping first can blank the frame on mobile)
    const vw=videoRef.current.videoWidth;
    const vh=videoRef.current.videoHeight;
    // Resize to max 1024px longest side — keeps payload lean without losing label detail
    const maxDim=1024;
    const scale=Math.min(1,maxDim/Math.max(vw,vh));
    const canvas=document.createElement('canvas');
    canvas.width=Math.round(vw*scale);
    canvas.height=Math.round(vh*scale);
    canvas.getContext('2d').drawImage(videoRef.current,0,0,canvas.width,canvas.height);
    const dataUrl=canvas.toDataURL('image/jpeg',0.82);
    const b64=dataUrl.split(',')[1];
    // Stop stream after capture
    if(streamRef.current) streamRef.current.getTracks().forEach(t=>t.stop());
    setCapturedImg(dataUrl);
    setPhase('processing');
    if(mode==='list') processListCapture(b64);
    else processLabelCapture(b64);
  }

  async function processLabelCapture(b64){
    try{
      const text=await window.claude.complete({messages:[{role:'user',content:[
        {type:'image',source:{type:'base64',media_type:'image/jpeg',data:b64}},
        {type:'text',text:LABEL_PROMPT}
      ]}]});
      const wine=JSON.parse(text.replace(/```json|```/g,'').trim());
      if(wine.error==='no_wine_label') throw new Error('no_wine_label');
      sessionStorage.setItem('vinterest_scan_result',JSON.stringify({demo:false,wine,confidence:0.95}));
    }catch(e){
      sessionStorage.setItem('vinterest_scan_result',JSON.stringify({demo:true,reason:e.message}));
    }finally{ nav('identified'); }
  }

  async function processListCapture(b64){
    try{
      const text=await window.claude.complete({max_tokens:8192,messages:[{role:'user',content:[
        {type:'image',source:{type:'base64',media_type:'image/jpeg',data:b64}},
        {type:'text',text:LIST_PROMPT}
      ]}]});
      // Robustly extract JSON — handles extra prose, code fences, truncation
      let cleaned=text.replace(/```json|```/g,'').trim();
      const s=cleaned.indexOf('{'); const e=cleaned.lastIndexOf('}');
      if(s>=0&&e>s) cleaned=cleaned.slice(s,e+1);
      const data=JSON.parse(cleaned);
      if(data.error) throw new Error(data.error);
      // Normalise compact keys (n/t/r/c/v/p) to full names
      const raw=data.wines||data.wine_list||data.results||[];
      const wines=raw.map(w=>({
        name:w.name||w.n||'Unknown',
        type:w.type||w.t||'red',
        region:w.region||w.r||'',
        country:w.country||w.c||'',
        vintage:w.vintage||w.v||null,
        price:w.price||w.p||''
      }));
      if(!wines.length) throw new Error('no_wines_found');
      sessionStorage.setItem('vinterest_winelist_result',JSON.stringify({demo:false,wines}));
    }catch(e){
      sessionStorage.setItem('vinterest_winelist_result',JSON.stringify({demo:true,reason:e.message}));
    }finally{ nav('winelist'); }
  }

  // ── Processing state ──
  if(phase==='processing'){
    return(
      <div style={{flex:1,background:'#0A0A0A',display:'flex',flexDirection:'column',alignItems:'center',justifyContent:'center',gap:28,padding:'0 32px',position:'relative'}}>
        <div onClick={back} style={{position:'absolute',top:16,left:20,width:38,height:38,borderRadius:19,background:'rgba(255,255,255,0.08)',display:'flex',alignItems:'center',justifyContent:'center',cursor:'pointer'}}>
          <Icon n="back" sz={18} col="#fff"/>
        </div>
        {capturedImg&&(
          <div style={{width:'70%',aspectRatio:'2/3',borderRadius:16,overflow:'hidden',border:`2px solid ${C.cr}`,boxShadow:`0 0 40px ${C.cr}35`}}>
            <img src={capturedImg} alt="" style={{width:'100%',height:'100%',objectFit:'cover'}}/>
          </div>
        )}
        <div style={{display:'flex',flexDirection:'column',alignItems:'center',gap:12}}>
          <div style={{width:44,height:44,borderRadius:22,border:'3px solid rgba(255,255,255,0.1)',borderTopColor:C.cr,animation:'vspin 0.85s linear infinite'}}/>
          <span style={{fontSize:19,fontWeight:700,color:'#fff',fontFamily:C.P}}>{mode==='list'?'Analysing wine list…':'Analysing label…'}</span>
          <span style={{fontSize:15,color:'rgba(255,255,255,0.4)',fontFamily:C.P}}>Identifying {mode==='list'?'wines':'wine'} with AI</span>
        </div>
        <style>{`@keyframes vspin{to{transform:rotate(360deg)}}`}</style>
      </div>
    );
  }

  // ── Viewfinder state ──
  return(
    <div style={{flex:1,display:'flex',flexDirection:'column',background:'#0A0A0A',position:'relative',overflow:'hidden'}}>
      {/* Camera feed */}
      {!camErr?(
        <video ref={videoRef} autoPlay playsInline muted style={{position:'absolute',inset:0,width:'100%',height:'100%',objectFit:'cover',opacity:.88}}/>
      ):(
        <div style={{position:'absolute',inset:0,background:'linear-gradient(135deg,#1a1a1a,#2d1b2e)',display:'flex',alignItems:'center',justifyContent:'center',flexDirection:'column',gap:8}}>
          <Icon n="camera" sz={42} col="rgba(255,255,255,0.18)"/>
          <span style={{fontSize:15,color:'rgba(255,255,255,0.3)',fontFamily:C.P}}>Camera unavailable in preview</span>
        </div>
      )}

      {/* Top bar */}
      <div style={{position:'relative',zIndex:3,display:'flex',justifyContent:'space-between',alignItems:'center',padding:'16px 20px',flexShrink:0}}>
        <div onClick={back} style={{width:38,height:38,borderRadius:19,background:'rgba(0,0,0,0.45)',backdropFilter:'blur(8px)',display:'flex',alignItems:'center',justifyContent:'center',cursor:'pointer'}}>
          <Icon n="back" sz={18} col="#fff"/>
        </div>
        <span style={{fontSize:18,fontWeight:600,color:'#fff',fontFamily:C.P}}>Scan Wine</span>
        <div style={{width:38,height:38}}/>
      </div>

      {/* Large portrait framing box */}
      <div style={{flex:1,position:'relative',zIndex:2,display:'flex',alignItems:'center',justifyContent:'center'}}>
        <div style={{width:mode==='list'?'95%':'80%',aspectRatio:mode==='list'?'2/3':'2/3.2',maxHeight:mode==='list'?'87vh':'64vh',position:'relative'}}>
          {/* Dim overlay outside frame */}
          <div style={{position:'absolute',top:0,left:0,right:0,bottom:0,boxShadow:'0 0 0 2000px rgba(0,0,0,0.52)',pointerEvents:'none',zIndex:1}}/>
          {/* Corner brackets */}
          {[[0,0],[1,0],[0,1],[1,1]].map(([x,y],i)=>(
            <div key={i} style={{
              position:'absolute',zIndex:2,
              [y?'bottom':'top']:-2,[x?'right':'left']:-2,
              width:48,height:48,
              borderTop:y?'none':`3px solid ${C.cr}`,
              borderBottom:y?`3px solid ${C.cr}`:'none',
              borderLeft:x?'none':`3px solid ${C.cr}`,
              borderRight:x?`3px solid ${C.cr}`:'none',
              borderRadius:y?(x?'0 0 10px 0':'0 0 0 10px'):(x?'0 10px 0 0':'10px 0 0 0')
            }}/>
          ))}
          {/* Instruction inside frame */}
          <div style={{position:'absolute',bottom:16,left:0,right:0,textAlign:'center',zIndex:2}}>
            <span style={{fontSize:15,color:'rgba(255,255,255,0.7)',fontFamily:C.P,background:'rgba(0,0,0,0.48)',padding:'5px 14px',borderRadius:20,backdropFilter:'blur(4px)'}}>
              {mode==='list'?'Frame the wine list':'Frame the wine label'}
            </span>
          </div>
        </div>
      </div>

      {/* Bottom controls */}
      <div style={{position:'relative',zIndex:3,padding:'0 20px 44px',display:'flex',flexDirection:'column',alignItems:'center',gap:20,flexShrink:0}}>
        {/* Mode toggle */}
        <div style={{display:'inline-flex',background:'rgba(0,0,0,0.55)',borderRadius:10,overflow:'hidden',backdropFilter:'blur(12px)'}}>
          {['Bottle','Wine List'].map((m,i)=>(
            <div key={i} onClick={()=>setMode(i===0?'bottle':'list')} style={{padding:'10px 24px',background:(i===0?mode==='bottle':mode==='list')?C.cr:'transparent',fontSize:16,fontWeight:600,color:(i===0?mode==='bottle':mode==='list')?'#fff':'rgba(255,255,255,0.45)',fontFamily:C.P,cursor:'pointer',transition:'background .18s'}}>{m}</div>
          ))}
        </div>
        {/* Capture button */}
        <div onClick={capturePhoto} style={{width:74,height:74,borderRadius:37,background:'rgba(255,255,255,0.92)',border:'4px solid rgba(255,255,255,0.35)',display:'flex',alignItems:'center',justifyContent:'center',cursor:'pointer',boxShadow:'0 4px 28px rgba(0,0,0,0.5)'}}>
          <div style={{width:56,height:56,borderRadius:28,background:C.cr}}/>
        </div>
      </div>
    </div>
  );
}

/* ── WINE IDENTIFIED ── */
function WineIdentifiedScreen({nav,back}){
  const existingRating=(scanData&&scanData.existingRating)||0;
  const [score,setScore]=React.useState(existingRating);
  const [saved,setSaved]=React.useState(existingRating>0);
  const scoreLabel=score===0?'':score<=20?'Not for me':score<=40?"It's ok":score<=60?'Good':score<=80?'Really good':'Exceptional';

  function handleScore(val){
    const v=Number(val);
    setScore(v);
    if(v>0&&wine&&!scanData.demo){
      if(existingRating>0){
        // Re-rating an existing wine — update without incrementing times_consumed
        WineHistory.rate(wine.name,wine.vintage,v);
      } else {
        WineHistory.add(wine,v);
      }
      setSaved(true);
    }
  }

  // Read scan result written by ScanScreen
  const scanData=React.useMemo(()=>{
    try{ return JSON.parse(sessionStorage.getItem('vinterest_scan_result')||'{}'); }
    catch(e){ return {}; }
  },[]);
  const wine=scanData.wine||null;
  const confidence=scanData.confidence||null;

  // Display values — real data when available, sensible demo fallback otherwise
  const displayName  = wine?.name         || 'Château Margaux';
  const displaySub   = wine
    ? `${wine.vintage||'NV'} · ${wine.region}, ${wine.country}`
    : '2018 · Bordeaux, France';
  const displayGrape = wine?.grapes?.[0]  || 'Cabernet Blend';
  const displayPrice = wine ? `$${wine.price_usd}` : '$180–220';
  const displayRating= wine ? `${wine.community_rating}★` : '4.7★';
  const matchPct     = confidence ? Math.round(Math.min(0.98,confidence)*100) : 94;

  const isDemo = scanData.demo === true;
  const scanReason = scanData.reason || '';

  return(
    <div style={{flex:1,display:'flex',flexDirection:'column',background:C.bg,overflowY:'auto'}}>
      {/* Debug / status banner — shows what actually happened */}
      {isDemo && (
        <div style={{background:'#FFF3CD',borderBottom:'1px solid #FFE082',padding:'10px 16px',display:'flex',alignItems:'flex-start',gap:10,flexShrink:0}}>
          <span style={{fontSize:19,flexShrink:0}}>⚠️</span>
          <div style={{flex:1}}>
            <div style={{fontSize:15,fontWeight:600,color:'#7A5200',fontFamily:C.P}}>
              {scanReason==='no_wine_label'&&'Label not detected — move closer and retake'}
              {scanReason==='camera_not_ready'&&'Point camera at a label and tap capture'}
              {scanReason&&!['camera_not_ready','no_wine_label'].includes(scanReason)&&`Error: ${scanReason.slice(0,80)}`}
              {!scanReason&&'Add ANTHROPIC_API_KEY in Netlify → Environment variables'}
            </div>
            {(scanReason==='no_wine_label'||scanReason==='camera_not_ready')&&(
              <div onClick={()=>nav('scan')} style={{marginTop:6,display:'inline-flex',alignItems:'center',gap:5,padding:'6px 14px',borderRadius:20,background:'#8B1A2F',cursor:'pointer'}}>
                <Icon n="camera" sz={12} col="#fff"/>
                <span style={{fontSize:14,fontWeight:700,color:'#fff',fontFamily:C.P}}>Try Again</span>
              </div>
            )}
          </div>
        </div>
      )}
      {!isDemo && (
        <div style={{background:'#E8F5E9',borderBottom:'1px solid #C8E6C9',padding:'6px 16px',display:'flex',alignItems:'center',gap:6,flexShrink:0}}>
          <span style={{fontSize:16}}>✓</span>
          <span style={{fontSize:14,fontWeight:600,color:C.green,fontFamily:C.P}}>Scanned from real label via Claude Vision</span>
        </div>
      )}
      <div style={{background:C.cr,padding:'16px 20px',display:'flex',alignItems:'center',gap:12,flexShrink:0}}>
        <div style={{width:34,height:34,borderRadius:17,background:'rgba(255,255,255,0.2)',display:'flex',alignItems:'center',justifyContent:'center'}}>
          <Icon n="check" sz={18} col="#fff"/>
        </div>
        <div style={{flex:1}}>
          <div style={{fontSize:19,fontWeight:700,color:'#fff',fontFamily:C.P}}>Wine Identified!</div>
          <div style={{fontSize:14,color:'rgba(255,255,255,0.65)',fontFamily:C.P}}>Tap for full details</div>
        </div>
        <div onClick={back} style={{cursor:'pointer'}}><Icon n="back" sz={20} col="rgba(255,255,255,0.6)"/></div>
      </div>

      <div style={{padding:'16px 20px',display:'flex',flexDirection:'column',gap:12}}>
        <Card style={{padding:16}}>
          <div style={{display:'flex',gap:14,alignItems:'flex-start'}}>
            <div style={{width:54,height:76,borderRadius:10,background:C.crSoft,flexShrink:0,display:'flex',alignItems:'center',justifyContent:'center',border:`1px solid ${C.crDim}`}}>
              <Icon n="wine" sz={26} col={C.cr}/>
            </div>
            <div style={{flex:1}}>
              <div style={{fontSize:22,fontWeight:700,color:C.ink,fontFamily:C.P,lineHeight:1.2}}>{displayName}</div>
              <div style={{fontSize:15,color:C.mid,fontFamily:C.P,marginTop:2}}>{displaySub}</div>
              <div style={{display:'flex',gap:5,marginTop:8,flexWrap:'wrap'}}>
                <Pill active sm style={{textTransform:'capitalize'}}>{wine?.type||'Red'}</Pill><Pill sm>{displayGrape}</Pill>
              </div>
            </div>
          </div>
        </Card>

        <div style={{display:'flex',gap:8}}>
          {[{l:'Your Match',v:`${matchPct}%`,col:C.green,bg:C.greenBg},{l:'Community',v:displayRating,col:C.amber,bg:C.amberBg},{l:'Price Range',v:displayPrice,col:C.ink2,bg:C.white}].map((s,i)=>(
            <div key={i} style={{flex:1,background:s.bg,borderRadius:12,padding:'10px 6px',textAlign:'center',border:`1px solid ${C.line}`}}>
              <div style={{fontSize:19,fontWeight:700,color:s.col,fontFamily:C.P}}>{s.v}</div>
              <div style={{fontSize:8.5,color:C.mid,fontFamily:C.P,marginTop:1}}>{s.l}</div>
            </div>
          ))}
        </div>

        <Card style={{background:C.greenBg,boxShadow:'none',border:`1px solid ${C.green}25`,padding:12}}>
          <div style={{fontSize:15,fontWeight:600,color:C.green,fontFamily:C.P,marginBottom:4}}>Why you'll love this</div>
          <div style={{fontSize:15,color:C.ink2,fontFamily:C.P,lineHeight:1.55}}>Full-bodied with dark fruit and earthy notes — matches your preference for structured Bordeaux-style reds.</div>
        </Card>

        {/* Score slider rating */}
        <Card style={{padding:'14px 16px'}}>
          <div style={{fontSize:15,fontWeight:600,color:C.ink,fontFamily:C.P,marginBottom:12}}>Rate This Wine</div>
          {/* Quick preset buttons */}
          <div style={{display:'flex',gap:5,marginBottom:12}}>
            {[20,40,60,80,100].map(p=>(
              <div key={p} onClick={()=>handleScore(p)} style={{flex:1,padding:'7px 2px',borderRadius:9,border:`1.5px solid ${score===p?C.cr:C.line}`,background:score===p?C.cr:'transparent',textAlign:'center',cursor:'pointer',transition:'all .15s'}}>
                <span style={{fontSize:16,fontWeight:700,color:score===p?'#fff':C.mid,fontFamily:C.P}}>{p}</span>
              </div>
            ))}
          </div>
          {/* Slider */}
          <input type="range" min="0" max="100" step="1" value={score}
            onChange={e=>handleScore(e.target.value)}
            style={{width:'100%',accentColor:C.cr,cursor:'pointer',marginBottom:10,display:'block'}}/>
          {/* Score display */}
          <div style={{textAlign:'center',minHeight:52,display:'flex',flexDirection:'column',alignItems:'center',justifyContent:'center',gap:2}}>
            {score>0?(
              <>
                <div style={{display:'flex',alignItems:'baseline',gap:3}}>
                  <span style={{fontSize:38,fontWeight:800,color:C.cr,fontFamily:C.P,lineHeight:1}}>{score}</span>
                  <span style={{fontSize:17,color:C.mid,fontFamily:C.P}}>/100</span>
                </div>
                <span style={{fontSize:15,fontWeight:600,color:C.amber,fontFamily:C.P}}>{scoreLabel}</span>
              </>
            ):(
              <span style={{fontSize:14,color:C.mid,fontFamily:C.P}}>Drag slider or tap a preset to rate</span>
            )}
          </div>
          {saved&&<div style={{textAlign:'center',fontSize:14,color:C.green,fontFamily:C.P,fontWeight:600,marginTop:8}}>✓ Saved to My Wines</div>}
        </Card>

        <Btn primary full onClick={()=>nav('detail')}>See Full Details &amp; Learn More</Btn>
        <Btn full onClick={()=>{try{navigator.share&&navigator.share({title:'Château Margaux 2018 on Vinterest',text:'Check out this wine I found! 🍷',url:'https://vinterest.app'})}catch(e){}}}>Share This Wine</Btn>
        <div style={{height:8}}/>
      </div>
    </div>
  );
}

Object.assign(window,{HomeScreen,ScanScreen,WineIdentifiedScreen});
