// Builds site-dist/: the marketing site for vinterest.app, separate from the app (`npm run build`
// builds the app into dist/). Run with `npm run site:build`.
//
//   site/index.html, privacy.html, terms.html   pages (templates: %%TOKENS%% are filled in below)
//   site/site.css, site/site.js                 the look, the scroll choreography, the beta form
//   site/demo/*                                 the demos: the app's own sources (scripts/app-sources.mjs,
//                                               minus pwa-app.jsx, which would boot the whole app) plus a
//                                               memory-only store and the demo screens, bundled as demo.js
//                                               and loaded only when a demo is about to be seen
//   site/_worker.js                             the beta sign-up endpoint (/api/beta), then static assets
//
// Settings (Cloudflare Pages build variables, all optional):
//   CF_ANALYTICS_TOKEN    Cloudflare Web Analytics token; without it no analytics script is added
//   SITE_ORIGIN           the site's public address, for share cards and the sitemap (default https://vinterest.app)
import * as esbuild from 'esbuild';
import { createHash } from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { APP_SOURCES } from './app-sources.mjs';
import { appVersion, collectAssetPaths, inlineAssets, transformSource, buildFonts } from './build.mjs';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const SITE = path.join(ROOT, 'site');
const OUT = path.join(ROOT, 'site-dist');

// The app's sources without the file that mounts the app, with the demo's storage right after Store.
const DEMO_SOURCES = [
  ...APP_SOURCES.flatMap((f) => (f === 'pwa-app.jsx' ? [] : f === 'pwa-store.js' ? [f, 'site/demo/store.js'] : [f])),
  'site/demo/demos.jsx',
];

const read = (rel) => fs.readFileSync(path.join(ROOT, rel), 'utf8');
const hash = (s) => createHash('sha256').update(s).digest('hex').slice(0, 10);

async function buildDemoBundle() {
  const version = appVersion();
  const vendor = await esbuild.build({
    stdin: {
      contents: [
        "import * as React from 'react';",
        "import * as ReactDOM from 'react-dom';",
        "import * as ReactDOMClient from 'react-dom/client';",
        'window.React = React;',
        'window.ReactDOM = Object.assign({}, ReactDOM, ReactDOMClient);',
      ].join('\n'),
      resolveDir: ROOT,
      sourcefile: 'vendor-react.js',
    },
    bundle: true, format: 'iife', minify: true, legalComments: 'none',
    define: { 'process.env.NODE_ENV': '"production"' },
    write: false,
  });
  const assets = inlineAssets(collectAssetPaths(DEMO_SOURCES));
  const parts = [
    `/* Vinterest website demos, from app ${version}. Generated by scripts/site.mjs, do not edit. */`,
    vendor.outputFiles[0].text,
    `const __VINTEREST_ASSETS__ = Object.freeze(${JSON.stringify(assets)});`,
  ];
  for (const file of DEMO_SOURCES) {
    const code = await transformSource(file, version);
    parts.push(`/* ---- ${file} ---- */\n${code}`);
  }
  // Minified: it is one big script the visitor downloads once, near the first demo.
  const min = await esbuild.transform(parts.join('\n'), { minify: true, legalComments: 'none', charset: 'utf8' });
  return min.code;
}

async function minify(file, loader) {
  const { code } = await esbuild.transform(read(file), { loader, minify: true, charset: 'utf8', legalComments: 'none' });
  return code;
}

function fill(html, vars) {
  const out = html.replace(/%%([A-Z_]+)%%/g, (m, k) => {
    if (!(k in vars)) throw new Error(`site: unknown token ${m}`);
    return vars[k];
  });
  return out;
}

async function build() {
  const origin = (process.env.SITE_ORIGIN || 'https://vinterest.app').replace(/\/+$/, '');
  fs.rmSync(OUT, { recursive: true, force: true });
  fs.mkdirSync(OUT, { recursive: true });

  const demo = await buildDemoBundle();
  const css = await minify('site/site.css', 'css');
  const js = await minify('site/site.js', 'js');
  fs.writeFileSync(path.join(OUT, 'demo.js'), demo);
  fs.writeFileSync(path.join(OUT, 'site.css'), css);
  fs.writeFileSync(path.join(OUT, 'site.js'), js);

  const token = process.env.CF_ANALYTICS_TOKEN;
  const vars = {
    ORIGIN: origin,
    CSS_V: hash(css), JS_V: hash(js), DEMO_V: hash(demo),
    ANALYTICS: token
      ? `<script defer src="https://static.cloudflareinsights.com/beacon.min.js" data-cf-beacon='{"token": "${token}"}'></script>`
      : '',
  };
  for (const page of ['index.html', 'privacy.html', 'terms.html']) {
    const dest = page === 'index.html' ? 'index.html' : page.replace('.html', '/index.html');
    fs.mkdirSync(path.dirname(path.join(OUT, dest)), { recursive: true });
    fs.writeFileSync(path.join(OUT, dest), fill(read(`site/${page}`), vars));
  }

  for (const rel of ['logo.png', 'icons', 'site/_headers', 'site/_worker.js']) {
    const dest = rel.startsWith('site/') ? rel.slice(5) : rel;
    fs.cpSync(path.join(ROOT, rel), path.join(OUT, dest), { recursive: true });
  }
  // The share card, if one has been made (npm run site:og).
  if (fs.existsSync(path.join(SITE, 'og.png'))) fs.copyFileSync(path.join(SITE, 'og.png'), path.join(OUT, 'og.png'));
  fs.writeFileSync(path.join(OUT, 'robots.txt'), `User-agent: *\nAllow: /\nSitemap: ${origin}/sitemap.xml\n`);
  fs.writeFileSync(path.join(OUT, 'sitemap.xml'),
    `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n` +
    ['/', '/privacy/', '/terms/'].map((p) => `  <url><loc>${origin}${p}</loc></url>\n`).join('') + `</urlset>\n`);
  buildFonts(OUT);

  console.log(`Built site-dist/ — demo.js ${(demo.length / 1024).toFixed(0)} KB, site.js ${(js.length / 1024).toFixed(0)} KB, site.css ${(css.length / 1024).toFixed(0)} KB${token ? ', analytics on' : ', no analytics token'}`);
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  build().catch((err) => { console.error(err.message || err); process.exit(1); });
}
