/* Writes data/world-map.json: the land and country borders behind Mastery's region map, one
   drawing per view (Europe, North America, …), clipped to that view and projected (Mercator) to a
   W-wide box, so the app draws plain SVG paths and places a region's pin from its `at` [lat, lng]
   in data/knowledge.json with the same projection (KnowledgeMap.project). Natural Earth 1:50m via
   world-atlas. Run after changing a view: npm run map. The output is committed. */
import fs from 'node:fs';
import { createRequire } from 'node:module';
import { feature, merge, mesh } from 'topojson-client';
import { geoMercator, geoPath } from 'd3-geo';

const require = createRequire(import.meta.url);
const world = require('world-atlas/countries-50m.json');
// Drawn at twice the phone's width and rounded to whole units (half a pixel on screen), with
// repeated points and specks under MIN_RING units across dropped, to keep app.js small.
const W = 680, MIN_RING = 3;
// [west, south, east, north] in degrees. Every knowledge-base region must fall inside one view.
const VIEWS = [
  { id: 'europe', label: 'Europe', box: [-10.5, 35.2, 27.5, 51.6] },
  { id: 'north-america', label: 'North America', box: [-127, 32, -72, 51.5] },
  { id: 'south-america', label: 'South America', box: [-76.5, -41, -61.5, -27] },
  { id: 'oceania', label: 'Australia & NZ', box: [112, -47.5, 179.5, -27] },
  { id: 'south-africa', label: 'South Africa', box: [16.5, -35.2, 21.5, -32] },
];

/* Douglas–Peucker: drops points closer than TOLERANCE units to the line their neighbours make. */
const TOLERANCE = 1;
function simplify(pts) {
  if (pts.length < 3) return pts;
  const keep = new Uint8Array(pts.length); keep[0] = keep[pts.length - 1] = 1;
  const stack = [[0, pts.length - 1]];
  while (stack.length) {
    const [a, b] = stack.pop(); let far = -1, best = TOLERANCE;
    const [ax, ay] = pts[a], [bx, by] = pts[b], dx = bx - ax, dy = by - ay, len = Math.hypot(dx, dy);
    for (let i = a + 1; i < b; i++) {
      const [px, py] = pts[i];
      const d = len ? Math.abs(dy * px - dx * py + bx * ay - by * ax) / len : Math.hypot(px - ax, py - ay);
      if (d > best) { best = d; far = i; }
    }
    if (far >= 0) { keep[far] = 1; stack.push([a, far], [far, b]); }
  }
  return pts.filter((_, i) => keep[i]);
}

/* Rounds each point to a whole unit, drops a point equal to the one before it, simplifies, and
   (for land) drops rings too small to see. */
function tidy(d, closed) {
  if (!d) return '';
  return d.split(/(?=M)/).map((part) => {
    let pts = []; let last = null;
    for (const m of part.matchAll(/(-?[\d.]+),(-?[\d.]+)/g)) {
      const p = [Math.round(+m[1]), Math.round(+m[2])], key = p.join(',');
      if (key !== last) { pts.push(p); last = key; }
    }
    pts = simplify(pts);
    const xs = pts.map((p) => p[0]), ys = pts.map((p) => p[1]);
    if (pts.length < 2 || (closed && (pts.length < 4 || Math.max(Math.max(...xs) - Math.min(...xs), Math.max(...ys) - Math.min(...ys)) < MIN_RING))) return '';
    return 'M' + pts.map((p) => p.join(',')).join('L') + (closed ? 'Z' : '');
  }).join('');
}

const rad = (d) => (d * Math.PI) / 180;
const Y = (lat) => Math.log(Math.tan(Math.PI / 4 + rad(lat) / 2));
const land = merge(world, world.objects.countries.geometries);
const borders = mesh(world, world.objects.countries, (a, b) => a !== b);
const regions = JSON.parse(fs.readFileSync('data/knowledge.json', 'utf8')).regions;

const views = VIEWS.map((v) => {
  const [w, s, e, n] = v.box;
  const k = W / rad(e - w);
  const h = Math.round(k * (Y(n) - Y(s)));
  const proj = geoMercator().scale(k).translate([-k * rad(w), k * Y(n)]).clipExtent([[0, 0], [W, h]]);
  const path = geoPath(proj).digits(0);
  return { id: v.id, label: v.label, box: v.box, w: W, h, land: tidy(path(land), true), borders: tidy(path(borders), false) };
});

const inside = (v, [lat, lng]) => lng >= v.box[0] && lng <= v.box[2] && lat >= v.box[1] && lat <= v.box[3];
const lost = Object.entries(regions).filter(([, r]) => !r.at || !views.some((v) => inside(v, r.at))).map(([n]) => n);
if (lost.length) throw new Error('Regions outside every view (or with no "at"): ' + lost.join(', '));

const out = { _about: 'Generated by scripts/world-map.mjs from Natural Earth 1:50m (public domain). Do not edit.', views };
fs.writeFileSync('data/world-map.json', JSON.stringify(out) + '\n');
console.log(views.map((v) => `${v.id} ${v.w}×${v.h} ${((v.land.length + v.borders.length) / 1024).toFixed(1)}KB`).join('\n'));
